### ISSUE TITLE
documentation not really clear...

### ISSUE THREAD

**Issue by gb5256** [supplyhog/yii2-slug-parser#1]
Hi, 
I would really like to use this but the documentation is not clear (at least not for me).
I do not get it to work.

for example:
**SimpleSlugUrlRule**
'If you use SimpleSlugUrlRule it will handle slugs that are on a table'.
Does that mean that the the other options are not using tables?

**Suggested scheme**

```
slug
model_class
model_key
model_value
```

Does that mean that I have to create a table called "slug" with three columns?

**And finally I get an error message:**

```
Please set the slugClass to a model that implements \supplyhog\SlugParser\SlugInterface
```

But I do have this in my model class:

```
class Article extends \yii\db\ActiveRecord implements SlugInterface
```

Can you give me some more information on the above?
thanks.

**Comment by wilwade** [comment]
@gb5256 The SlugInterface is only needed if you want a table to hold all your slugs that point to different models.

It sounds like you only have the Article model that you want slugs for correct?

If so the Url Rule config should look something like:

`[
    'class' => 'supplyhog\SlugParser\SimpleSlugUrlRule',
    'modelClass' => 'common\models\Article',
    'controller' => 'app\controllers\ArticleController',
    'route' => 'article',
    'modelField' => 'slug',
    'modelKey' => 'id',
],`

**Comment by gb5256** [comment]
Hi, 
thanks for your reply. Really appreciated.

I am not using just one model and I also would like to use a slug table for all the slugs.
so this is my setup right now (for now just with the article as slugable)

main.php:

```
    'urlManager' => [
        //'enablePrettyUrl' => true,
        //'showScriptName' => false,
        'class' => 'supplyhog\SlugParser\CompositeSlugUrlRule',
        'rules' => [
            [ 
                'class' => 'supplyhog\SlugParser\SlugUrlRule', 
                'modelClass' => 'frontend\models\Article', 
                'controller' => 'frontend\controllers\ArticleController', 
                'route' => 'article', 
                'defaultAction' => 'view' //The default action if nothing else is used. 
            ],
        ]
    ],
```

and in the model "article':

```
namespace frontend\models;
use supplyhog\SlugParser\SlugInterface;
use Yii;
class Article extends \yii\db\ActiveRecord implements SlugInterface
{ ....
```

and the error message is this:

```
Invalid Configuration – yii\base\InvalidConfigException
Please set the slugClass to a model that implements \supplyhog\SlugParser\SlugInterface
```

**Comment by wilwade** [comment]
@gb5256 Sorry for the late response. The "slugClass" is a different property on the CompositeSlugUrlRule that had been left out of the README. It is corrected now:

```
$config[‘urlManager’]['rules'][] = [
  'class' => 'supplyhog\SlugParser\CompositeSlugUrlRule',
  //'minLength' => 8 //Set the minimum require length of the slug default 8 
  'slugClass' => 'common\models\Slug', //The class that impliments the SlugInterface
```
